spring:
  application:
    name: ASTERUM-SYSTEM-BACKEND
    version: v.1.0.0
  datasource:
    url: jdbc:h2:file:./data/asterum;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

server:
  port: 8083
